-- 0012_group_api.sql — docs/04 §3, docs/02 §1, docs/14 §7. tasks/E02-03.
--
-- Two functions the `groups` handler cannot do correctly from TypeScript: one because the
-- answer lives in a Postgres catalog, one because it has to be atomic.

-- ─── timezone_is_valid ───────────────────────────────────────────────────────
-- docs/14 §7: the timezone is validated against `pg_timezone_names` and never interpolated
-- into SQL. A group's timezone is fixed for the life of the group and every round it will
-- ever have is materialised through it (docs/02 §1), so an unusable value here is not a bad
-- request, it is a group that can never have a round.
create or replace function public.timezone_is_valid(p_timezone text)
returns boolean
language sql
stable
as $$
  select exists (select 1 from pg_timezone_names where name = p_timezone)
$$;

revoke all on function public.timezone_is_valid(text) from public, anon, authenticated;
grant execute on function public.timezone_is_valid(text) to service_role;

-- ─── create_group ────────────────────────────────────────────────────────────
-- The group row and its creator's admin membership are one fact, so they are one
-- transaction. Split across two PostgREST calls, a failure between them leaves a group with
-- no members and an invite code nobody can use.
--
-- Two failures are distinguished by SQLSTATE, because the handler answers them differently:
--   BD001         the caller already has an active membership → 409 ALREADY_IN_GROUP
--   23505 (other) the invite code collided → the handler retries with a fresh code
--
-- The invite code is generated by the caller rather than here: docs/14 §8 wants a CSPRNG, and
-- `gen_random_bytes` in plpgsql would put the alphabet in two places.
create or replace function public.create_group(
  p_user        uuid,
  p_name        text,
  p_timezone    text,
  p_reveal_hour int,
  p_invite_code text
) returns public.groups
language plpgsql
as $$
declare
  v_group public.groups;
begin
  -- ADR-005, one group per user. The partial unique index below is what actually enforces
  -- it under a race; this check is here so the common case gets the right error code.
  if exists (select 1 from public.memberships
             where user_id = p_user and left_at is null) then
    raise exception 'caller already has an active membership' using errcode = 'BD001';
  end if;

  insert into public.groups (name, timezone, reveal_hour, invite_code, created_by)
  values (btrim(p_name), p_timezone, p_reveal_hour, p_invite_code, p_user)
  returning * into v_group;

  begin
    insert into public.memberships (group_id, user_id, role)
    values (v_group.id, p_user, 'admin');
  exception when unique_violation then
    -- Only `memberships_one_active_per_user` can fire here, and only if a concurrent request
    -- created a group between the check above and this insert.
    raise exception 'caller already has an active membership' using errcode = 'BD001';
  end;

  return v_group;
end $$;

comment on function public.create_group(uuid, text, text, int, text) is
  'Creates a group and its creator''s admin membership in one transaction. Raises BD001 when '
  'the caller is already in a group (ADR-005); lets 23505 through so the handler can retry '
  'with a fresh invite code.';

revoke all on function public.create_group(uuid, text, text, int, text) from public, anon, authenticated;
grant execute on function public.create_group(uuid, text, text, int, text) to service_role;
